project:
  type: book
  output-dir: _output
toc: false
book:
  title: ""
  chapters:
    - index.qmd
    - shell-table.qmd
    - shell-listing.qmd


format:
  docx:
    reference-doc: "C:/Users/zhushuai/OneDrive/Work Yeedo/Other/template/shell-template.docx"
    lang: zh
    number-sections: false
    keep-md: true
    pandoc:
      from: markdown-short_subsuperscripts
    filters:
      - docx_crossref.lua   
